# Generated by Django 3.0.8 on 2020-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('slot', models.AutoField(primary_key=True, serialize=False)),
                ('car', models.CharField(max_length=10)),
            ],
        ),
    ]
